### ISSUE TITLE
multithreaded installation

### ISSUE THREAD

**Issue by knaaptime** [UDST/pandana#104]
I'm pretty sure I've got multithreaded installation working with openmp and clang on osx by using the [conda toolchain](https://docs.conda.io/projects/conda-build/en/latest/source/resources/compiler-tools.html?highlight=clang) and changing the `extra_link_args` in setup.py to `'-fopenmp=libiomp5'`, (that is, everything compiles and runs great)

but it looks like the library no longer outputs the diagnostic message that tells the user how many threads are in use. Is it possible to invoke that somehow so I can see whether its working? Thanks!

**Comment by smmaurer** [comment]
This sounds neat, I'm going to try it out! Do you know if this would let us distribute Conda builds that are automatically multithreaded on OS X?

I just opened a draft PR that restores the thread count diagnostic message, among other things. I'm not sure why it was removed, probably a mistake. 

You can restore it locally by tweaking `src/graphalg.cpp` and `src/shared.h` like this: https://github.com/UDST/pandana/pull/109/files#diff-b5456dd6223748303b0929471b1231ed.

**Comment by knaaptime** [comment]
ah, thanks for the tip on getting the diagnostics back. thats helpful


>This sounds neat, I'm going to try it out! Do you know if this would let us distribute Conda builds that are automatically multithreaded on OS X?

that was my expectation, though i'm wondering if somehow clang is the culprit causing trouble with #107

**Comment by smmaurer** [comment]
Update:

Installing Pandana from Conda Forge now provides multi-threading on OS X (as well as other platforms), beginning with v0.4.3.

And we've added instructions to the documentation for setting up the same compilation toolchain locally: http://udst.github.io/pandana/installation.html#compiling-locally

Big thanks to @knaaptime for opening this issue! I'm closing it now as fully resolved.

**Comment by knaaptime** [comment]
🙌 this is awesome, thanks for all your hard work on this!
