### ISSUE TITLE
replace use of basemap

### ISSUE THREAD

**Issue by sablanchard** [UDST/pandana#110]
`basemap` is being depreciated in favor of `cartopy` and support will end in 2020. `basemap` should be considered for replacement in the plot function. Per https://github.com/UDST/pandana/issues/70#issuecomment-497974062 and [basemap announcement](https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement)

**Comment by smmaurer** [comment]
See issue #144
