### ISSUE TITLE
Planning v0.5 release

### ISSUE THREAD

**Issue by smmaurer** [UDST/pandana#139]
This issue is to plan the v0.5 release of Pandana.

### Previously merged PR's

These PR's have been merged subsequent to v0.4.4, and will be included in this release:

- PR #131 (fixing an installation bug)
- PR #135 (fixing a matplotlib backend bug)
- PR #134 (adding a shortest-path-length function)
- PR #136 (vectorized shortest path lengths for many OD pairs)
- PR #137 (compilation fixes for MacOS 10.15 Catalina)

### Additional things to include

- [x] update documentation
- [x] add placeholder compilation settings for MacOS 11 Big Sur
- [x] fix issue #133 (reinstating alternate names for aggregation types)
- [x] drop scikit-learn requirement
- [x] make matplotlib and osmnet optional
- [x] update versioning, etc.

Anything else to include? 

I believe `network.plot()` is pretty broken at the moment, because it relies on an old Matplotlib extension called Basemap that’s now deprecated and hard to install (see issue #110). But I think it's better to get the existing updates released right now, and put that off until later.

**Comment by thinkersloo** [comment]
Hey, Is there a way to not simplify the Pandana network from bbox. I mean when API is called the data is further narrowed to fewer nodes and edges.... I want the network with every node and edges, possible?

**Comment by sablanchard** [comment]
Hi @thinkersloo ! I think you are referring to the OSMnet package here: https://github.com/UDST/osmnet that generates the network. If you want to open up a issue on OSMnet with an example of a small network that is missing nodes/edges with an example of the same network that has the missing nodes/edges we can take a look at it to reproduce. Pointing out which nodes/edges are missing in the example would be helpful.

**Comment by thinkersloo** [comment]
> Hi @thinkersloo ! I think you are referring to the OSMnet package here: https://github.com/UDST/osmnet that generates the network. If you want to open up a issue on OSMnet with an example of a small network that is missing nodes/edges with an example of the same network that has the missing nodes/edges we can take a look at it to reproduce. Pointing out which nodes/edges are missing in the example would be helpful.

Hi @sablanchard ,

I have already opened an [issue](https://github.com/UDST/osmnet/issues/24#issue-656467104) about 2 weeks ago. 
It will be very grateful if you provide me some resolution.

Thanks!
