### ISSUE TITLE
gtfs import

### ISSUE THREAD

**Issue by fscottfoti** [UDST/pandana#36]
Do the same as with OSM import but for transit (will also need to connect the transit network to the walking network)

**Comment by rafapereirabr** [comment]
Hi guys. Would you have an idea of when Pandana will be able to use GTFS data as an input?

**Comment by jiffyclub** [comment]
Someone is thinking about it, but I think it may be a substantial amount of work so no promises on a date.

**Comment by rafapereirabr** [comment]
Thank you Matt.  I would love to try it when it is ready. One of the case studies of my PhD will be a before and after comparison of transport investments in the city of Rio (Brazil) and how these investments will change the accessibility landscape of the city.

**Comment by waddell** [comment]
Sam Maurer is now working on this at UC Berkeley, so stay tuned.

**Comment by waddell** [comment]
I meant Sam Blanchard...

**Comment by Holisticnature** [comment]
This would be interesting to see. Will this thread be updated if it is added?

**Comment by sablanchard** [comment]
Thank you David. Yes we have a new tool called UrbanAccess that will soon be released on UDST that does this. The tool takes GTFS data and provides tools to validate, subset, and calculate impedance and convert it to a Pandana network. It is almost ready for release and we will update this issue once it is available.

**Comment by Holisticnature** [comment]
Excellent thanks for the update.

**Comment by sablanchard** [comment]
@Holisticnature and @rafapereirabr a new GTFS and OSM pedestrian network creation tool (currently in alpha) has been released recently that addresses this issue, it is located in a separate repo called UrbanAccess: https://github.com/UDST/urbanaccess and is specifically designed to produce integrated GTFS and pedestrian networks for use with Pandana. I will close this issue.

**Comment by Holisticnature** [comment]
That works with me. I think the work around with NetworkX is sufficient. Might just want to add a method that uses those ideas though. 

I have taking a look at Urban Access, and I really like what I see. The Feed class looks really useful. 

Thanks. Please close the issue. I might contribute at a later date.

**Comment by rafapereirabr** [comment]
I'm happy with this as well. Good job Sam !
