### ISSUE TITLE
import pandana on windows results in "ImportError: DLL load failed..." error

### ISSUE THREAD

**Issue by sablanchard** [UDST/pandana#49]
I am running 64-bit Windows 7 with python 2.7.11 and have installed pandana 0.2.0 via pip - this is a new install of pandana on a machine that has never had it. When I import pandana I receive the following error, any ideas on what may be wrong here?:

import pandana as pdna

---

ImportError                               Traceback (most recent call last)
<ipython-input-3-eb353b7e0ad1> in <module>()
----> 1 import pandana as pdna

C:\Users\samb\Anaconda2\lib\site-packages\pandana__init__.py in <module>()
----> 1 from network import Network
      2 
      3 version = **version** = '0.2.0'

C:\Users\samb\Anaconda2\lib\site-packages\pandana\network.py in <module>()
      8 import pandas as pd
      9 
---> 10 from . import _pyaccess
     11 from .loaders import pandash5 as ph5
     12 

ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

**Comment by jiffyclub** [comment]
It's clearly a problem with the compiled C extension, but I have no idea what that error message means. You may need to figure out how to compile Pandana from source.

**Comment by sablanchard** [comment]
Ok thanks. I am not experienced with windows compiling so this may have to wait for quite sometime for me to try. If I do Ill let you know the outcome.

**Comment by jiffyclub** [comment]
It's an adventure, let me tell you.

**Comment by waddell** [comment]
Probably best to focus on running this on a Linux platform for the near term...

**Comment by Eh2406** [comment]
@semcogli an I hit this error on linux yesterday. Both from pip and from source. We set up a new vm in order to do a clean test. but have not had time to get back to it.

**Comment by pksohn** [comment]
I wonder if it's the same reason why the [Appveyor builds](https://ci.appveyor.com/project/pksohn/pandana/build/1.0.16) are failing.

**Comment by federicofernandez** [comment]
I think it's a different error in Appveyor.

**Comment by Eh2406** [comment]
New VM with linux Mint. 
Install anaconda2. 
$ conda config --add channels udst
$ conda config --add channels conda-forge
$ conda install pandana
in python `import pandana` works.

That is what I have time for, new Edit to come.

**Comment by bstabler** [comment]
see  #92

**Comment by sablanchard** [comment]
Closing this issue for now. New version 0.4.1 installed without issue via pip and conda on windows in both python 27 and 3. Can reopen if same issue occurs on new version.
