### ISSUE TITLE
nearest_pois() discrepancy between version 0.2.0 and 0.2dev

### ISSUE THREAD

**Issue by mxndrwgrdnr** [UDST/pandana#57]
Trying to generate poi's for bayarea_urbansim on two different machines yielded two different sets of results, despite the underlying data files being the same. Debugging ultimately led me to determine that different versions of Pandana, one installed from pip and the other installed from the source using **setup.py**, was the source of the problem. The reason I'm raising an issue here is that the version of Pandana installed from source, 0.2dev, doesn't seem to be working properly. The `nearest_pois()` function was returning the value of the `max_distance` parameter for every source node for every poi, indicating that no poi's were found. The same exact code with the same exact underlying data files returned different results, with poi's found, once I rolled Pandana back to version 0.2.0. Don't know enough about the differences between the version of Pandana that's on pip and the one that you get when you install from the source, but it might be worth looking into.

**Comment by pksohn** [comment]
@mxndrwgrdnr Can you send me the code and some sample data you're seeing this discrepancy with? I can't reproduce this yet with simple test cases.

**Comment by mxndrwgrdnr** [comment]
Sorry, pretty sure this issue is handled by #58 (closed) and #62. I'm going to close it.
