### ISSUE TITLE
init_pois on multiple network graphs?

### ISSUE THREAD

**Issue by semcogli** [UDST/pandana#60]
I built two networks for nearest distance queries. One is for regional wide auto access, the other is for local walking access. I can built two networks without problem using "reserve_num_graphs" option. However, "init_pois" only works for the first network not the second (which network is irrelevant) . Running "init_pois" command on the second network will cause kernel death on Linux. I guess it is related to C++ limitation? Any idea on how to get this around?

Thanks.

**Comment by fscottfoti** [comment]
You are correct.  That should be a quick fix, I think.

**Comment by fscottfoti** [comment]
@semcogli check out the PR mentioned here - hopefully this fixes your problem

**Comment by semcogli** [comment]
@fscottfoti I can confirm the fix works. Thanks!

**Comment by sablanchard** [comment]
Fixed with #61
