### ISSUE TITLE
Link broken in Pandana tutorial in docs

### ISSUE THREAD

**Issue by janowicz** [UDST/pandana#66]
It was reported that the link to sample data file in the Pandana tutorial is currently not working:

https://github.com/UDST/pandana/blob/master/docs/tutorial.rst

https://s3-us-west-2.amazonaws.com/urbandatascience/pandana/osm_bayarea.h5

**Comment by fscottfoti** [comment]
I certainly have that file - do you need it?  Do you have somewhere you want to put it?

**Comment by janowicz** [comment]
Ah cool!  If you send it to me, I can put it in the same s3 bucket that the synthpop pums files live in and then update the link.
