### ISSUE TITLE
add optional precompute parameter to take a list of discrete impedance values or range of values

### ISSUE THREAD

**Issue by sablanchard** [UDST/pandana#69]
precompute currently is set up to only accept a 0 to n range of values for the precomputation process. It would be a great feature to not only have this as a option but to allow for precompute of multiple ranges and discrete single values in a list. This is particularly useful when dealing with very complex and large networks at the pedestrian scale when say you are only ever interested in a small set of values such as 10, 20, 30, 40 minute travel times or a set of different value ranges such as 2000-3000 m and 5000-6000 m. Otherwise a lot of processing time is wasted on values that one may never be interested in especially in the lower bound of the values. The precompute for units other than distance, such as minutes, for large pedestrian scale networks tend to take too long and is a waste of computation resources when only a subset of values will be examined anyway. This assumes that the underlying processes called in precompute can skip certain ranges of values.

**Comment by fscottfoti** [comment]
Hmm, to be clear, precompute doesn't precompute the aggregations, it computes and saves the nodes that are available within a distance.  So if you were doing an aggregation within 3000 meters you would need all the nodes within 3000 meters.  I don't think you're saying you want to do an aggregation with a hole in the middle, like a donut right?  At any rate, there wouldn't be any way to save time - you'd still have to traverse all the nodes in the graph on your way out, and you'd just optimize the nodes you save, which would save memory.  I'm not sure there's a way to speed up what you're asking for - doing regional queries at the pedestrian scale does indeed take a lot of time.  Let me know if I'm misinterpreting.

**Comment by sablanchard** [comment]
@fscottfoti ah yes that is right all the nodes < the value still need to be traversed so it seems that a speed up cannot be achieved. Figuring out a way to pickle the pre-computed network seems to be the best option then. Will close the feature request unless there are any other ideas on this topic.
