### ISSUE TITLE
Tutorial Question concerning set_pois, pandana 0.3.0

### ISSUE THREAD

**Issue by apiszcz** [UDST/pandana#82]
the x,y variables are not defined, I tried 'x','y' and ['x','y'] which produce other pandas errors.

```
net.set_pois("restaurants", x, y)
produces
*** NameError: name 'x' is not defined


import pandas as pd
import pandana as pdna
store = pd.HDFStore('osm_bayarea.h5', "r")
nodes = store.nodes
edges = store.edges
print(nodes.head(3))
print(edges.head(3))
net=pdna.Network(nodes["x"], nodes["y"], edges["from"], edges["to"],edges[["weight"]])
net.precompute(3000)
net.init_pois(num_categories=1, max_dist=2000, max_pois=10)
net.set_pois("restaurants", x, y)
```

**Comment by apiszcz** [comment]
Are the assignments missing from the tutorial?

y=nodes.y
x=nodes.x

**Comment by sablanchard** [comment]
Hello!
The tutorial [here](http://udst.github.io/pandana/tutorial.html#assign-variables-and-perform-computations-for-nearest-queries) says `This code initializes the “restaurants” category with the positions specified by the x and y columns (which are Pandas Series). ` The tutorial does not explicitly create the x and y series but instructs you that that is what they are. In the actual code demonstration [here](https://github.com/UDST/pandana/blob/master/examples/Example.ipynb) shows the full workflow and the creation of the x and y series in code.

Will close this unless there an issue with this.
