### ISSUE TITLE
KeyError: "['weight'] not in index"

### ISSUE THREAD

**Issue by jucajuca** [UDST/pandana#86]
Hi I'm trying the pandanas network tool. 
I already ran the SF bay area example. 
I'm trying to do the same analysis with data in Vienna. 

```python
# Bounding box 
tmp = [16.169815,48.113391,16.589355,48.327496]

# Reordered for Pandana functions
bbox = [tmp[1], tmp[0], tmp[3], tmp[2]]

poi_df = osm.node_query(*bbox, tags='amenity=restaurant')
x, y = poi_df['lon'], poi_df['lat']

network_wien = osm.pdna_network_from_bbox(*bbox, network_type='walk', two_way=True, timeout=600, max_query_area_size=2500000000)

pandash5.network_to_pandas_hdf5(network_wien, './osm_wien.h5')
```

When I try to run the example I get the following error:
KeyError: "['weight'] not in index"

Am I missing something ?

#### Environment 

- Operating system: ubuntu 16.04
- Python version: 2.7
- Pandana version: lastest

#### Paste the error message (if applicable):
```python
Traceback (most recent call last):
  File "tutorial_example_vienna.py", line 69, in <module>
    edges[["weight"]])
  File "/home/jccb/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "/home/jccb/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/jccb/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['weight'] not in index"
Closing remaining open files:./osm_wien.h5...done
```

**Comment by jucajuca** [comment]
I looked into the h5 file. Instead of "weight" it has a key called "distance". 
Is there a reason for the difference or does this come from the OSM import?

**Comment by fscottfoti** [comment]
Which example are you referring to?  It looks like distance is the name of the impedance returned from OSM import, but weight is common too.

**Comment by kuanb** [comment]
@jucajuca I believe the OSM network returns a distance column, which you can use to create a weight column. For example, if you want the measure of your impedance to be time, you could take the distance column and divide it by some value that you've determined as your travel speed and assign that to a new column you call "weight."

**Comment by jucajuca** [comment]
cool, thank you for the explanation
