### ISSUE TITLE
Pandana tutorial comes with NameError: name 'x' is not defined 

### ISSUE THREAD

**Issue by barguzin** [UDST/pandana#90]
If you encounter a bug in Pandana please: 1) first search the previously opened issues to see if the problem has already been reported; 2) If not, fill in the template below and tag with the appropriate `Type` label. You can delete any sections that do not apply.

#### Description of the bug
---------------------------------------------------------------------------
Trying to follow tutorial described at https://udst.github.io/pandana/tutorial.html

#### Network data (optional) 
If the issue is related to specific network data please provide a link to download the data or the function used to download the data.

#### Environment 

- Operating system:

- Python version: 2.7

- Pandana version: 0.4

- Pandana required packages versions (optional):

#### Paste the code that reproduces the issue here:

```python
import pandas as pd
import pandana as pdna
store = pd.HDFStore('D:/2017/py_tu/osm_bayarea.h5', "r")
nodes = store.nodes
edges = store.edges
print nodes.head(3)
print edges.head(3)
net=pdna.Network(nodes["x"], nodes["y"], edges["from"], edges["to"],
                 edges[["weight"]])
net.precompute(3000)
net.set_pois("restaurants", 2000, 10, x, y)
```

#### Paste the error message (if applicable):
```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-3fc5423cc35e> in <module>()
----> 1 net.set_pois("restaurants", 2000, 10, x, y)

NameError: name 'x' is not defined

```

**Comment by d3netxer** [comment]
I am getting this same error message!

**Comment by semcogli** [comment]
You need to load a restaurant POI file with 'x' and 'y' columns. Otherwise, the network module won't know what to query about.

**Comment by sablanchard** [comment]
Hi @barguzin, @semcogli is correct you need to have `x` and `y` columns in your poi data for `set_poi()` to work. See the api for more information: http://udst.github.io/pandana/network.html?highlight=set_pois#pandana.network.Network.set_pois. Will close this issue.
